# Generated by Django 4.2.5 on 2023-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_product_options_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/product_images/thumbnail/"
            ),
        ),
    ]
