# Generated by Django 4.2.5 on 2023-10-10 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="merchant_id",
            new_name="payment_intent",
        ),
    ]
